spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.101:3306/hello
    username: mpw:yRbmyda4upm0+I0t08l2+g==
    password: mpw:SdpnaoKzmaymZZgURaVG8g==
server:
  port: 9001
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl
      table-underline: true
      capital-mode: true
      logic-delete-field: delete_flag
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty