spring:
  profiles:
    active: dev
  datasource:
    # HikariConfig
    hikari:
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
      # 最小空闲连接
      minimum-idle: 3
      # 最大连接数
      maximum-pool-size: 10
      # 最大空闲时间
      idle-timeout: 600000
      # 最大生命时间
      max-lifetime: 1800000
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      table-underline: true
      capital-mode: true
      logic-delete-field: delete_flag
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0
  config-location: classpath:/mybatis-config.xml
  # mapper和dao都扫描扫描进系统后会自动关联起来
  mapper-locations: [classpath:/mapper/**/*.xml]
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:2XS0qR/q+KSxL17iZ4GzZN/QYhNBLFY3ObK1t5DVpZYULp1q4WLCFW5RreVG8mVHe0HvdP9tWXtbxUMdrOj7pZ2uHT479pJ8Gk5GNKaf8JxZvBWv2mLd44Yjqq/m44ls
    username: mpw:yRbmyda4upm0+I0t08l2+g==
    password: mpw:SdpnaoKzmaymZZgURaVG8g==
server:
  port: 9001
logging:
  level:
    # 必须加在mapper的包上
    com.haha.wormholeadmin.mapper: debug
